added games
letsgamedev/gamesengine pull request #37
Opened 2017-07-13 18:04 UTC by UnknownSoldier1

Ich habe die folgenden Spiele hinzugefügt:
Pokemon GO, Planet Coaster, Elite: Dangerous, Ori and the Blind Forest,
Ori and the Will of the Wisps, PAYDAY: The Heist, PAYDAY 2, PREY, Rust
und Subnautica

2017-07-13 18:06 UTC, UnknownSoldier1 commented
Zu Ori and the Will of the Wisps sei gesagt: Das Spiel hat bisher kein bekanntes Release-Datum. Da es derzeit jedoch noch kein Feature für "Release Datum Unbekannt" gibt habe ich erstmal meine eigene Schätzung da rein gesetzt, welche aber vermutlich falsch sein wird.

2017-07-13 19:55 UTC, AnnsAnns requested changes
Du fügst 2 Engines hinzu, die in script.js nicht makiert sind - Bitte füge beide in script.js ein, sonst sind das 2 Error Links

2017-07-13 20:10 UTC, UnknownSoldier1 commented
Wurde gemacht.

2017-07-15 09:38 UTC, letsgamedev commented
Bitte nutze für alle Spiele INGAME material

2017-07-17 09:36 UTC, letsgamedev commented
Habs nun per Hand bei mir eingepflegt

2017-07-17 09:36 UTC, closed without merging